# Install dependencies only when needed
FROM node:16.14-alpine3.15
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat git
WORKDIR /app
COPY . .

RUN yarn install --immutable
RUN yarn low build

ENV NODE_ENV production
ENV HIGH_BANDWITH_URL http://localhost:3000

EXPOSE 8080
ENV PORT 8080

CMD ["node", "server.js"]
